/*
 * This source file was generated by the Gradle 'init' task
 */
package example;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
        // Local classUnderTest = new Local();
    }
}
