[package]
name = "rust-lambda-graphql"
edition = "2021"


[dependencies]
async-graphql = "7.0.7"
lambda_http = "0.13.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.122"

tokio = { version = "1", features = ["macros"] }
