/*
 * This source file was generated by the Gradle 'init' task
 */
package example;

public class Local {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Local().getGreeting());
    }
}
