[package]
name = "rust-lambda-rest"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219" }
axum = { version = "0.8.4", default-features = false }
lambda_http = "0.15.1"
serde_json = "1.0.140"
tokio = { version = "1", features = ["macros"] }
