Resources:
  JSONPlaceHolder:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: jsonplaceholder
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      DeletionProtectionEnabled: false
