---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml

driver:
  name: default

platforms:
  - name: ec2-instance

provisioner:
  name: ansible
