---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml

driver:
  name: default

platforms:
  - name: ec2-instance-web
    groups:
      - example
      - web
  - name: ec2-instance-api
    groups:
      - example
      - api
  - name: ec2-instance-batch
    groups:
      - example
      - batch

provisioner:
  name: ansible

scenario:
  name: default
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
