---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml

driver:
  name: default

platforms:
  - name: ec2-instance
    groups:
      - example

provisioner:
  name: ansible

scenario:
  name: default
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
