---
- name: Verify
  hosts:
    - ec2-instance-web
    - ec2-instance-api
    - ec2-instance-batch
  gather_facts: false
  tasks:
    - name: Replace this task with one that validates your content
      ansible.builtin.debug:
        msg: "This is the effective test"
