[versions]
junit-bom = "5.10.0"
aws-lambda-java-core = "1.2.3"
aws-lambda-java-events = "3.14.0"
jackson = "2.18.2"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-bom" }
aws-lambda-java-core = { module = "com.amazonaws:aws-lambda-java-core", version.ref = "aws-lambda-java-core" }
aws-lambda-java-events = { module = "com.amazonaws:aws-lambda-java-events", version.ref = "aws-lambda-java-events" }
jackson = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
