[versions]


[libraries]
junit-bom = { module = "org.junit:junit-bom", version = "5.10.0" }
aws-lambda-java-core = { module = "com.amazonaws:aws-lambda-java-core", version = "1.2.3" }
aws-lambda-java-events = { module = "com.amazonaws:aws-lambda-java-events", version = "3.14.0" }
jackson = { module = "com.fasterxml.jackson.core:jackson-databind", version = "2.18.2" }
