[package]
name = "rust-cognito"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.5.10"
aws-sdk-cognitoidentityprovider = "1.59.0"
base64 = "0.22.1"
dotenvy = "0.15.7"
hmac = "0.12.1"
sha2 = "0.10.8"
tokio = { version = "1.42.0", features = ["full"] }
