[project]
name = "ansible-packer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.40.25",
    "botocore>=1.40.25",
    "molecule-plugins[ec2]>=25.8.12",
]
