name: Unit Test (Workspace)

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  NODE_VERSION: "22.x"

jobs:
  test:
    name: Unit Test (Node.js)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i

      - name: Run Unit Test in all packages
        run: pnpm -r run test

  lint:
    name: Lint (Node.js)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 22.x

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i

      - name: Run Lint in all packages
        run: pnpm -r run lint
